name: Automated Server Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_server_tests:
    name: Run server tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Node.js '16.x'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Run tests
        run: npm run test-ci
        env:
          CI: true
          FIREBASE_ADMIN_PROJECT_ID: ${{ secrets.FIREBASE_ADMIN_PROJECT_ID }}
          FIREBASE_ADMIN_PRIVATE_KEY: ${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
          FIREBASE_ADMIN_CLIENT_EMAIL: ${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}
